name: Build Monaca App for Android and iOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Monaca CLI
      run: npm install -g monaca

    - name: Login to Monaca
      env:
        MONACA_EMAIL: ${{ secrets.MONACA_EMAIL }}
        MONACA_PASSWORD: ${{ secrets.MONACA_PASSWORD }}
      run: monaca login --email $MONACA_EMAIL --password $MONACA_PASSWORD